### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by AC75007344** [octo-woapi/api-with-springboot#3]
Hello,

While running the build command, i'm having the following error

> C:\WORKSPACE\api-with-springboot>gradle clean build
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> A problem occurred configuring root project 'api-with-springboot'.
> > Could not resolve all artifacts for configuration ':classpath'.
>    > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:2.0.1.RELEASE.
>      Required by:
>          project :
>       > Could not resolve org.springframework.boot:spring-boot-gradle-plugin:2.0.1.RELEASE.
>          > Could not get resource 'https://repo.maven.apache.org/maven2/org/springframework/boot/spring-
> boot-gradle-plugin/2.0.1.RELEASE/spring-boot-gradle-plugin-2.0.1.RELEASE.pom'.
>             > Could not GET 'https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-g
> radle-plugin/2.0.1.RELEASE/spring-boot-gradle-plugin-2.0.1.RELEASE.pom'.
>                > repo.maven.apache.org
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log o
> utput. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 3s

Thank you

**Comment by TCHdvlp** [comment]
Hello,

Can you have access to resources via your browser ? 
https://repo.maven.apache.org/maven2/org/springframework/boot/spring-boot-gradle-plugin/2.0.1.RELEASE/spring-boot-gradle-plugin-2.0.1.RELEASE.pom

Don't have any proxxy that can prevent you to access those files ?

**Comment by TCHdvlp** [comment]
No info, no follow up. Closing
